"""empty message

Revision ID: d181f9063afa
Revises: 9ef827a90d8f
Create Date: 2022-03-14 13:28:15.034486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd181f9063afa'
down_revision = '9ef827a90d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('question_id', sa.Integer(), nullable=True))
    op.add_column('answer', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('answer', sa.Column('create_date', sa.DateTime(), nullable=False))
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_column('answer', 'question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('question', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'question', ['question'], ['id'], ondelete='CASCADE')
    op.drop_column('answer', 'create_date')
    op.drop_column('answer', 'content')
    op.drop_column('answer', 'question_id')
    # ### end Alembic commands ###
